[general]
import = [ '~/.config/alacritty/colorschemes/tokyonight_night.toml' ]

[env]
  TERM = 'xterm-256color'

[window]
  dynamic_padding = true
  opacity = 1.0
  title = 'Alacritty'

  [window.class]
    general = 'Alacritty'
    instance = 'Alacritty'

  [window.padding]
    x = 10
    y = 5

[font]
  size = 12.0

  [font.normal]
    family = 'FiraMono Nerd Font'
    style = 'Regular'

  [font.bold]
    family = 'FiraMono Nerd Font'
    style = 'Bold'

  [font.italic]
    family = 'FiraMono Nerd Font'
    style = 'Italic'

  [font.bold_italic]
    family = 'FiraMono Nerd Font'
    style = 'Bold Italic'

[[keyboard.bindings]]
action = 'Paste'
key = 'V'
mods = 'Control|Shift'

[[keyboard.bindings]]
action = 'Copy'
key = 'C'
mods = 'Control|Shift'

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"
