# See https://wiki.hypr.land/Configuring/Window-Rules/ for more

# Picture-in-Picture
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, float on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, keep_aspect_ratio on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, move (monitor_w*0.73) (monitor_h*0.72)
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, size (monitor_w*0.25) (monitor_h*0.25)
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, pin on

# Wlogout blur
layerrule = match:namespace logout_dialog, blur on

# Dialog windows – float+center these windows.
windowrule = match:title ^(Open File)(.*)$, center on, float on
windowrule = match:title ^(Select a File)(.*)$, center on, float on
windowrule = match:title ^(Choose wallpaper)(.*)$, center on, float on
windowrule = match:title ^(Open Folder)(.*)$, center on, float on
windowrule = match:title ^(Save As)(.*)$, center on, float on
windowrule = match:title ^(Library)(.*)$, center on, float on
windowrule = match:title ^(File Upload)(.*)$, center on, float on
windowrule = match:title ^(.*)(wants to save)$, center on, float on
windowrule = match:title ^(.*)(wants to open)$, center on, float on
windowrule = match:title All Files$, center on, float on

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_initial_focus on
